
services:
  api:
    build: .
    ports: 
      - "8000:8000"
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Depine123
      DATABASE_USERNAME: postgres
      DATABASE_NAME: fastapi
      SECRET_KEY: 7e14c84ba93ef43d2977e2dc9d5a53657ef3bb583c5b25382c62f7b6940f1ec5
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Depine123
      POSTGRES_DB: fastapi
    ports:
      - "5433:5432"




